package pw.lemmmy.ts3protocol.declarations;

import lombok.RequiredArgsConstructor;

import java.util.HashMap;
import java.util.Map;

@RequiredArgsConstructor
public enum TS3Error {
    OK("unknown error code", 0x0000),
    UNDEFINED("undefined error", 0x0001),
    NOT_IMPLEMENTED("not implemented", 0x0002),
    OK_NO_UPDATE("", 0x0003),
    DONT_NOTIFY("", 0x0004),
    LIB_TIME_LIMIT_REACHED("library time limit reached", 0x0005),
    COMMAND_NOT_FOUND("command not found", 0x0100),
    UNABLE_TO_BIND_NETWORK_PORT("unable to bind network port", 0x0101),
    NO_NETWORK_PORT_AVAILABLE("no network port available", 0x0102),
    CLIENT_INVALID_ID("invalid clientid", 0x0200),
    CLIENT_NICKNAME_INUSE("nickname is already in use", 0x0201),
    CLIENT_INVALID_ERROR_CODE("invalid error code", 0x0202),
    CLIENT_PROTOCOL_LIMIT_REACHED("max clients protocol limit reached", 0x0203),
    CLIENT_INVALID_TYPE("invalid client type", 0x0204),
    CLIENT_ALREADY_SUBSCRIBED("already subscribed", 0x0205),
    CLIENT_NOT_LOGGED_IN("not logged in", 0x0206),
    CLIENT_COULD_NOT_VALIDATE_IDENTITY("could not validate client identity", 0x0207),
    CLIENT_INVALID_PASSWORD("invalid loginname or password", 0x0208),
    CLIENT_TOO_MANY_CLONES_CONNECTED("too many clones already connected", 0x0209),
    CLIENT_VERSION_OUTDATED("client version outdated, please update", 0x020A),
    CLIENT_IS_ONLINE("client is online", 0x020B),
    CLIENT_IS_FLOODING("client is flooding", 0x020C),
    CLIENT_HACKED("client is modified", 0x020D),
    CLIENT_CANNOT_VERIFY_NOW("can not verify client at this moment", 0x020E),
    CLIENT_LOGIN_NOT_PERMITTED("client is not permitted to log in", 0x020F),
    CLIENT_NOT_SUBSCRIBED("client is not subscribed to the channel", 0x0210),
    CHANNEL_INVALID_ID("invalid channelid", 0x0300),
    CHANNEL_PROTOCOL_LIMIT_REACHED("max channels protocol limit reached", 0x0301),
    CHANNEL_ALREADY_IN("already member of channel", 0x0302),
    CHANNEL_NAME_INUSE("channel name is already in use", 0x0303),
    CHANNEL_NOT_EMPTY("channel not empty", 0x0304),
    CHANNEL_CAN_NOT_DELETE_DEFAULT("can not delete default channel", 0x0305),
    CHANNEL_DEFAULT_REQUIRE_PERMANENT("default channel requires permanent", 0x0306),
    CHANNEL_INVALID_FLAGS("invalid channel flags", 0x0307),
    CHANNEL_PARENT_NOT_PERMANENT("permanent channel can not be child of non permanent channel", 0x0308),
    CHANNEL_MAXCLIENTS_REACHED("channel maxclient reached", 0x0309),
    CHANNEL_MAXFAMILY_REACHED("channel maxfamily reached", 0x030A),
    CHANNEL_INVALID_ORDER("invalid channel order", 0x030B),
    CHANNEL_NO_FILETRANSFER_SUPPORTED("channel does not support filetransfers", 0x030C),
    CHANNEL_INVALID_PASSWORD("invalid channel password", 0x030D),
    CHANNEL_IS_PRIVATE_CHANNEL("channel is private channel", 0x030E),
    CHANNEL_INVALID_SECURITY_HASH("invalid security hash supplied by client", 0x030F),
    SERVER_INVALID_ID("invalid serverid", 0x0400),
    SERVER_RUNNING("server is running", 0x0401),
    SERVER_IS_SHUTTING_DOWN("server is shutting down", 0x0402),
    SERVER_MAXCLIENTS_REACHED("server maxclient reached", 0x0403),
    SERVER_INVALID_PASSWORD("invalid server password", 0x0404),
    SERVER_DEPLOYMENT_ACTIVE("deployment active", 0x0405),
    SERVER_UNABLE_TO_STOP_OWN_SERVER("unable to stop own server in your connection class", 0x0406),
    SERVER_IS_VIRTUAL("server is virtual", 0x0407),
    SERVER_WRONG_MACHINEID("server wrong machineid", 0x0408),
    SERVER_IS_NOT_RUNNING("server is not running", 0x0409),
    SERVER_IS_BOOTING("server is booting up", 0x040A),
    SERVER_STATUS_INVALID("server got an invalid status for this operation", 0x040B),
    SERVER_MODAL_QUIT("server modal quit", 0x040C),
    SERVER_VERSION_OUTDATED("server version is too old for command", 0x040D),
    DATABASE("database error", 0x0500),
    DATABASE_EMPTY_RESULT("database empty result set", 0x0501),
    DATABASE_DUPLICATE_ENTRY("database duplicate entry", 0x0502),
    DATABASE_NO_MODIFICATIONS("database no modifications", 0x0503),
    DATABASE_CONSTRAINT("database invalid constraint", 0x0504),
    DATABASE_REINVOKE("database reinvoke command", 0x0505),
    PARAMETER_QUOTE("invalid quote", 0x0600),
    PARAMETER_INVALID_COUNT("invalid parameter count", 0x0601),
    PARAMETER_INVALID("invalid parameter", 0x0602),
    PARAMETER_NOT_FOUND("parameter not found", 0x0603),
    PARAMETER_CONVERT("convert error", 0x0604),
    PARAMETER_INVALID_SIZE("invalid parameter size", 0x0605),
    PARAMETER_MISSING("missing required parameter", 0x0606),
    PARAMETER_CHECKSUM("invalid checksum", 0x0607),
    VS_CRITICAL("virtual server got a critical error", 0x0700),
    CONNECTION_LOST("connection lost", 0x0701),
    NOT_CONNECTED("not connected", 0x0702),
    NO_CACHED_CONNECTION_INFO("no cached connection info", 0x0703),
    CURRENTLY_NOT_POSSIBLE("currently not possible", 0x0704),
    FAILED_CONNECTION_INITIALISATION("failed connection initialization", 0x0705),
    COULD_NOT_RESOLVE_HOSTNAME("could not resolve hostname", 0x0706),
    INVALID_SERVER_CONNECTION_HANDLER_ID("invalid server connection handler id", 0x0707),
    COULD_NOT_INITIALISE_INPUT_MANAGER("could not initialize input manager", 0x0708),
    CLIENTLIBRARY_NOT_INITIALISED("client library not initialized", 0x0709),
    SERVERLIBRARY_NOT_INITIALISED("server library not initialized", 0x070A),
    WHISPER_TOO_MANY_TARGETS("too many whisper targets", 0x070B),
    WHISPER_NO_TARGETS("no whisper targets found", 0x070C),
    FILE_INVALID_NAME("invalid file name", 0x0800),
    FILE_INVALID_PERMISSIONS("invalid file permissions", 0x0801),
    FILE_ALREADY_EXISTS("file already exists", 0x0802),
    FILE_NOT_FOUND("file not found", 0x0803),
    FILE_IO_ERROR("file input/output error", 0x0804),
    FILE_INVALID_TRANSFER_ID("invalid file transfer id", 0x0805),
    FILE_INVALID_PATH("invalid file path", 0x0806),
    FILE_NO_FILES_AVAILABLE("no files available", 0x0807),
    FILE_OVERWRITE_EXCLUDES_RESUME("overwrite excludes resume", 0x0808),
    FILE_INVALID_SIZE("invalid file size", 0x0809),
    FILE_ALREADY_IN_USE("file already in use", 0x080A),
    FILE_COULD_NOT_OPEN_CONNECTION("could not open file transfer connection", 0x080B),
    FILE_NO_SPACE_LEFT_ON_DEVICE("no space left on device (disk full?)", 0x080C),
    FILE_EXCEEDS_FILE_SYSTEM_MAXIMUM_SIZE("file exceeds file system's maximum file size", 0x080D),
    FILE_TRANSFER_CONNECTION_TIMEOUT("file transfer connection timeout", 0x080E),
    FILE_CONNECTION_LOST("lost file transfer connection", 0x080F),
    FILE_EXCEEDS_SUPPLIED_SIZE("file exceeds supplied file size", 0x0810),
    FILE_TRANSFER_COMPLETE("file transfer complete", 0x0811),
    FILE_TRANSFER_CANCELED("file transfer canceled", 0x0812),
    FILE_TRANSFER_INTERRUPTED("file transfer interrupted", 0x0813),
    FILE_TRANSFER_SERVER_QUOTA_EXCEEDED("file transfer server quota exceeded", 0x0814),
    FILE_TRANSFER_CLIENT_QUOTA_EXCEEDED("file transfer client quota exceeded", 0x0815),
    FILE_TRANSFER_RESET("file transfer reset", 0x0816),
    FILE_TRANSFER_LIMIT_REACHED("file transfer limit reached", 0x0817),
    SOUND_PREPROCESSOR_DISABLED("preprocessor disabled", 0x0900),
    SOUND_INTERNAL_PREPROCESSOR("internal preprocessor", 0x0901),
    SOUND_INTERNAL_ENCODER("internal encoder", 0x0902),
    SOUND_INTERNAL_PLAYBACK("internal playback", 0x0903),
    SOUND_NO_CAPTURE_DEVICE_AVAILABLE("no capture device available", 0x0904),
    SOUND_NO_PLAYBACK_DEVICE_AVAILABLE("no playback device available", 0x0905),
    SOUND_COULD_NOT_OPEN_CAPTURE_DEVICE("could not open capture device", 0x0906),
    SOUND_COULD_NOT_OPEN_PLAYBACK_DEVICE("could not open playback device", 0x0907),
    SOUND_HANDLER_HAS_DEVICE("serverconnectionhandler has a device registered", 0x0908),
    SOUND_INVALID_CAPTURE_DEVICE("invalid capture device", 0x0909),
    SOUND_INVALID_PLAYBACK_DEVICE("invalid clayback device", 0x090A),
    SOUND_INVALID_WAVE("invalid wave file", 0x090B),
    SOUND_UNSUPPORTED_WAVE("wave file type not supported", 0x090C),
    SOUND_OPEN_WAVE("could not open wave file", 0x090D),
    SOUND_INTERNAL_CAPTURE("internal capture", 0x090E),
    SOUND_DEVICE_IN_USE("device still in use", 0x090F),
    SOUND_DEVICE_ALREADY_REGISTERRED("device already registerred", 0x0910),
    SOUND_UNKNOWN_DEVICE("device not registered/known", 0x0911),
    SOUND_UNSUPPORTED_FREQUENCY("unsupported frequency", 0x0912),
    SOUND_INVALID_CHANNEL_COUNT("invalid channel count", 0x0913),
    SOUND_READ_WAVE("read error in wave", 0x0914),
    SOUND_NEED_MORE_DATA("sound need more data", 0x0915),
    SOUND_DEVICE_BUSY("sound device was busy", 0x0916),
    SOUND_NO_DATA("there is no sound data for this period", 0x0917),
    SOUND_CHANNEL_MASK_MISMATCH("channelmask set bits count (speakers) is not the same as (count)", 0x0918),
    PERMISSION_INVALID_GROUP_ID("invalid group id", 0x0A00),
    PERMISSION_DUPLICATE_ENTRY("duplicate entry", 0x0A01),
    PERMISSION_INVALID_PERM_ID("invalid permission id", 0x0A02),
    PERMISSION_EMPTY_RESULT("empty result set", 0x0A03),
    PERMISSION_DEFAULT_GROUP_FORBIDDEN("access to default group is forbidden", 0x0A04),
    PERMISSION_INVALID_SIZE("invalid size", 0x0A05),
    PERMISSION_INVALID_VALUE("invalid value", 0x0A06),
    PERMISSIONS_GROUP_NOT_EMPTY("group is not empty", 0x0A07),
    PERMISSIONS_CLIENT_INSUFFICIENT("insufficient client permissions", 0x0A08),
    PERMISSIONS_INSUFFICIENT_GROUP_POWER("insufficient group modify power", 0x0A09),
    PERMISSIONS_INSUFFICIENT_PERMISSION_POWER("insufficient permission modify power", 0x0A0A),
    PERMISSION_TEMPLATE_GROUP_IS_USED("template group is currently used", 0x0A0B),
    PERMISSIONS("permission error", 0x0A0C),
    ACCOUNTING_VIRTUALSERVER_LIMIT_REACHED("virtualserver limit reached", 0x0B00),
    ACCOUNTING_SLOT_LIMIT_REACHED("max slot limit reached", 0x0B01),
    ACCOUNTING_LICENSE_FILE_NOT_FOUND("license file not found", 0x0B02),
    ACCOUNTING_LICENSE_DATE_NOT_OK("license date not ok", 0x0B03),
    ACCOUNTING_UNABLE_TO_CONNECT_TO_SERVER("unable to connect to accounting server", 0x0B04),
    ACCOUNTING_UNKNOWN_ERROR("unknown accounting error", 0x0B05),
    ACCOUNTING_SERVER_ERROR("accounting server error", 0x0B06),
    ACCOUNTING_INSTANCE_LIMIT_REACHED("instance limit reached", 0x0B07),
    ACCOUNTING_INSTANCE_CHECK_ERROR("instance check error", 0x0B08),
    ACCOUNTING_LICENSE_FILE_INVALID("license file invalid", 0x0B09),
    ACCOUNTING_RUNNING_ELSEWHERE("virtualserver is running elsewhere", 0x0B0A),
    ACCOUNTING_INSTANCE_DUPLICATED("virtualserver running in same instance already", 0x0B0B),
    ACCOUNTING_ALREADY_STARTED("virtualserver already started", 0x0B0C),
    ACCOUNTING_NOT_STARTED("virtualserver not started", 0x0B0D),
    ACCOUNTING_TO_MANY_STARTS("", 0x0B0E),
    MESSAGE_INVALID_ID("invalid message id", 0x0C00),
    BAN_INVALID_ID("invalid ban id", 0x0D00),
    CONNECT_FAILED_BANNED("connection failed, you are banned", 0x0D01),
    RENAME_FAILED_BANNED("rename failed, new name is banned", 0x0D02),
    BAN_FLOODING("flood ban", 0x0D03),
    TTS_UNABLE_TO_INITIALIZE("unable to initialize tts", 0x0E00),
    PRIVILEGE_KEY_INVALID("invalid privilege key", 0x0F00),
    VOIP_PJSUA("", 0x1000),
    VOIP_ALREADY_INITIALIZED("", 0x1001),
    VOIP_TOO_MANY_ACCOUNTS("", 0x1002),
    VOIP_INVALID_ACCOUNT("", 0x1003),
    VOIP_INTERNAL_ERROR("", 0x1004),
    VOIP_INVALID_CONNECTIONID("", 0x1005),
    VOIP_CANNOT_ANSWER_INITIATED_CALL("", 0x1006),
    VOIP_NOT_INITIALIZED("", 0x1007),
    PROVISIONING_INVALID_PASSWORD("invalid password", 0x1100),
    PROVISIONING_INVALID_REQUEST("invalid request", 0x1101),
    PROVISIONING_NO_SLOTS_AVAILABLE("no(more) slots available", 0x1102),
    PROVISIONING_POOL_MISSING("pool missing", 0x1103),
    PROVISIONING_POOL_UNKNOWN("pool unknown", 0x1104),
    PROVISIONING_UNKNOWN_IP_LOCATION("unknown ip location(perhaps lan ip?)", 0x1105),
    PROVISIONING_INTERNAL_TRIES_EXCEEDED("internal error(tried exceeded)", 0x1106),
    PROVISIONING_TOO_MANY_SLOTS_REQUESTED("too many slots requested", 0x1107),
    PROVISIONING_TOO_MANY_RESERVED("too many reserved", 0x1108),
    PROVISIONING_COULD_NOT_CONNECT("could not connect to provisioning server", 0x1109),
    PROVISIONING_AUTH_SERVER_NOT_CONNECTED("authentication server not connected", 0x1110),
    PROVISIONING_AUTH_DATA_TOO_LARGE("authentication data too large", 0x1111),
    PROVISIONING_ALREADY_INITIALIZED("already initialized", 0x1112),
    PROVISIONING_NOT_INITIALIZED("not initialized", 0x1113),
    PROVISIONING_CONNECTING("already connecting", 0x1114),
    PROVISIONING_ALREADY_CONNECTED("already connected", 0x1115),
    PROVISIONING_NOT_CONNECTED("", 0x1116),
    PROVISIONING_IO_ERROR("io_error", 0x1117),
    PROVISIONING_INVALID_TIMEOUT("", 0x1118),
    PROVISIONING_TS3SERVER_NOT_FOUND("", 0x1119),
    PROVISIONING_NO_PERMISSION("unknown permissionid", 0x111A);
    
    public static final Map<Integer, TS3Error> ERROR_MAP = new HashMap<>();

    private final String message;
    private final int id;
    
    static {
        for (TS3Error value : values()) {
            ERROR_MAP.put(value.id, value);
        }
    }
}
